version: 2
general:
  branches:
    only:
     - master

.build_template: &build_steps
  steps:
    - checkout
    - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
    - run: bundle exec rspec

jobs:
  build_ruby2_3:
    <<: *build_steps
    docker:
      - image: ruby:2.3
  build_ruby2_4:
    <<: *build_steps
    docker:
      - image: ruby:2.4
  build_ruby2_5:
    <<: *build_steps
    docker:
      - image: ruby:2.5
  build_ruby2_6rc:
    <<: *build_steps
    docker:
      - image: ruby:2.6-rc

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build_ruby2_3
      - build_ruby2_4
      - build_ruby2_5
      - build_ruby2_6rc
